title: <p align="center"> Narendra Singh </p>
logo: /assets/img/nss.jpg
description: 
<p align="center">Give back to society. </p>
  <p align="center">
  <a href="https://www.linkedin.com/in/narendrasingh92/">LinkedIn</a> |
  <a href="https://github.com/iamnarendrasingh">GitHub</a>
  
  <br>   
      Less is More.
  <br>
</p>



theme: jekyll-theme-minimal